package com.helpdesk.entity.enums
enum class EventType {
    TICKET_CREATED,
    ML_PREDICTION_APPLIED,
    ML_PREDICTION_FAILED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    CATEGORY_CHANGED,
    ASSIGNEE_CHANGED,
    COMMENT_ADDED,
    TICKET_RESOLVED,
    TICKET_REOPENED,
    TICKET_CLOSED,
    TICKET_CANCELLED
}